// Run with the demo served at http://127.0.0.1:8765/.
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const artifacts = path.join(require('node:os').tmpdir(), 'team3-demo-checks');
fs.mkdirSync(artifacts, { recursive: true });
const { chromium } = require('C:/Users/ADMIN/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:8765/index.html');
  await page.getByRole('button', { name: 'Project Repository', exact: true }).click();
  assert.equal(await page.locator('.repo-project').count(), 6);
  await page.screenshot({ path: path.join(artifacts, 'repository-preview.png'), fullPage: true });
  await page.getByRole('button', { name: /Completed projects/ }).click();
  assert.equal(await page.locator('.repo-project').count(), 1);
  await page.locator('.repo-project').click();
  assert(await page.getByRole('heading', { name: 'All project documents' }).isVisible());
  await page.getByRole('button', { name: 'Final interior handover', exact: true }).click();
  assert(await page.locator('#modal').getByText('ILLUSTRATIVE DEMO DOCUMENT', { exact: true }).isVisible());
  await page.evaluate(() => closeModal());
  await page.evaluate(() => { repositorySection = 'ongoing'; go('repository'); });
  await page.locator('.repo-project').first().click();
  assert(await page.getByText('CURRENT RESPONSIBILITY').isVisible());
  assert(await page.getByRole('button', { name: 'Furniture & floor layout', exact: true }).first().isVisible());
  // Completion changes repository membership, without deleting any documents.
  const before = await page.evaluate(() => state.docs.filter(d => d.project === 'p4').length);
  await page.evaluate(() => completeDialog('p4'));
  await page.locator('#modal [name=note]').fill('Final handover confirmed for the demo.');
  await page.getByRole('button', { name: 'Mark completed', exact: true }).click();
  await page.evaluate(() => { repositorySection = 'completed'; go('repository'); });
  assert.equal(await page.locator('.repo-project').count(), 2);
  assert.equal(await page.evaluate(() => state.docs.filter(d => d.project === 'p4').length), before);
  await page.getByRole('button', { name: 'Employee Management', exact: true }).click();
  await page.screenshot({ path: path.join(artifacts, 'employees-preview.png'), fullPage: true });
  assert.equal(await page.locator('#employeeResults tbody tr').count(), 4);
  assert(await page.getByText('Idle', { exact: true }).isVisible());
  await page.getByRole('button', { name: 'Ravi K.', exact: true }).click();
  assert(await page.getByRole('heading', { name: 'Projects worked on' }).isVisible());
  await page.getByRole('button', { name: 'Month', exact: true }).click();
  assert((await page.locator('.calendar-day.worked').count()) > 1);
  const totals = await page.evaluate(() => { let [a,b] = periodBounds(); return activityMetrics('emp-3', a, b); });
  assert(Math.abs(totals.total - totals.working - totals.idle - totals.unknown) < 0.00001);
  assert(totals.idle > 0 && totals.days > 1);
  await page.screenshot({ path: path.join(artifacts, 'employee-month-preview.png'), fullPage: true });
  const reportDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export this period', exact: true }).click();
  const report = await reportDownload;
  assert(fs.readFileSync(await report.path(), 'utf8').includes('Idle hours'));
  assert(fs.readFileSync(await report.path(), 'utf8').includes('Ravi K.'));
  await page.getByRole('tab', { name: /Screenshots/ }).click();
  assert((await page.locator('.capture-card').count()) > 1);
  await page.screenshot({ path: path.join(artifacts, 'screenshots-preview.png'), fullPage: true });
  await page.locator('.capture-card').first().click();
  assert(await page.getByRole('heading', { name: 'Screenshot review', exact: true }).isVisible());
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download sample image' }).click();
  assert((await download).suggestedFilename().endsWith('.svg'));
  await page.evaluate(() => closeModal());
  await page.getByRole('button', { name: 'Screenshot settings', exact: true }).click();
  await page.locator('[name=interval]').fill('2');
  await page.locator('[name=unit]').selectOption('hours');
  await page.locator('[name=idle]').fill('7');
  await page.getByRole('button', { name: 'Save policy' }).click();
  assert.equal(await page.evaluate(() => state.capturePolicy.intervalMinutes), 120);
  assert.equal(await page.evaluate(() => state.capturePolicy.idleMinutes), 7);
  await page.reload();
  assert.equal(await page.evaluate(() => state.capturePolicy.intervalMinutes), 120);
  await page.evaluate(() => { openEmployee('emp-3'); workPeriod = 'day'; workDate = today(); render(); });
  await page.locator('.demo-controls summary').click();
  await page.getByRole('button', { name: 'Generate sample capture' }).click();
  const captureCount = await page.evaluate(() => state.captures.length);
  await page.evaluate(() => { const s=employeeSession('emp-3'); s.lastCaptureAt=Date.now()-121*60000; runSampleCaptureSchedule(); });
  assert.equal(await page.evaluate(() => state.captures.length), captureCount+1);
  await page.evaluate(() => { state.capturePolicy.enabled=false; employeeSession('emp-3').lastCaptureAt=0; runSampleCaptureSchedule(); });
  assert.equal(await page.evaluate(() => state.captures.length), captureCount+1);
  await page.evaluate(() => { state.capturePolicy.enabled=true; endEmployeeSession(employeeSession('emp-3').id); runSampleCaptureSchedule(); });
  assert.equal(await page.evaluate(() => state.captures.length), captureCount+1);
  // Employee creation is durable; quoted names are rendered as text.
  await page.evaluate(() => { go('employees'); addEmployeeDialog(); });
  await page.locator('[name=name]').fill("Anu O'Neil <Designer>");
  await page.locator('[name=email]').fill('anu@example.com');
  await page.locator('[name=team]').selectOption('Architect');
  await page.locator('#modal').getByRole('button', { name: 'Add employee', exact: true }).click();
  const newEmployeeId=await page.evaluate(() => selectedEmployee);
  assert.equal(await page.locator('h1').textContent(), "Anu O'Neil <Designer>");
  await page.locator('.demo-controls summary').click();
  await page.getByRole('button', { name: 'Simulate clock in' }).click();
  await page.locator('#modal [name=project]').selectOption('p0');
  await page.getByRole('button', { name: 'Start session' }).click();
  await page.evaluate(id => { const s=employeeSession(id); s.start-=3600000;s.activity[0].start=s.start; }, newEmployeeId);
  await page.locator('.demo-controls summary').click();
  await page.getByRole('button', { name: 'Simulate idle', exact: true }).click();
  assert.equal(await page.evaluate(id => employeeLive(employeeById(id)),newEmployeeId),'Idle');
  await page.evaluate(id => generateSampleCapture(id),newEmployeeId);
  const retainedCaptures=await page.evaluate(id=>state.captures.filter(c=>c.employeeId===id).length,newEmployeeId);
  await page.getByRole('button', { name: 'Remove employee', exact: true }).click();
  await page.locator('[name=reason]').fill('Demo removal; retain work history.');
  await page.locator('#modal').getByRole('button', { name: 'Remove employee', exact: true }).click();
  assert.equal(await page.evaluate(id => employeeById(id).active,newEmployeeId),false);
  assert.equal(await page.evaluate(id => !!employeeSession(id),newEmployeeId),false);
  assert.equal(await page.evaluate(id=>state.captures.filter(c=>c.employeeId===id).length,newEmployeeId),retainedCaptures);
  await page.reload();
  assert.equal(await page.evaluate(id => employeeById(id).active,newEmployeeId),false);
  // Removing a current assignee requires a same-team replacement.
  await page.evaluate(() => { openEmployee('emp-1'); removeEmployeeDialog('emp-1'); });
  assert(await page.locator('#modal [name=replacement]').isVisible());
  assert.equal(await page.locator('#modal [name=replacement] option').count(),1);
  await page.evaluate(() => { closeModal(); addEmployeeDialog(); });
  await page.locator('[name=name]').fill('New Architect');
  await page.locator('[name=email]').fill('new-architect@example.com');
  await page.locator('[name=team]').selectOption('Architect');
  await page.locator('#modal').getByRole('button',{name:'Add employee',exact:true}).click();
  const replacement=await page.evaluate(()=>selectedEmployee);
  await page.evaluate(()=>removeEmployeeDialog('emp-1'));
  await page.locator('[name=replacement]').selectOption(replacement);
  await page.locator('[name=reason]').fill('Transfer responsibility to the replacement architect.');
  await page.locator('#modal').getByRole('button',{name:'Remove employee',exact:true}).click();
  assert.equal(await page.evaluate(()=>stageOwner(project('p1'))),'New Architect');
  assert(await page.evaluate(()=>project('p1').history.at(-1).note.includes('New Architect')));
  // Date splitting includes midnight overlap once, and idle is bounded by the period.
  const boundary=await page.evaluate(id=>{let[a,b]=dayBounds(today());state.sessions.push({id:'boundary',employeeId:id,employee:employeeById(id).name,project:'p0',start:a-3600000,end:a+3600000,activity:[{kind:'working',start:a-3600000,end:a},{kind:'idle',start:a,end:a+3600000}]});return activityMetrics(id,a,b)},replacement);
  assert.equal(boundary.total,1);assert.equal(boundary.idle,1);assert.equal(boundary.working,0);assert.equal(boundary.days,1);
  await page.setViewportSize({width:390,height:844});
  for(const screen of ['repository','repositoryDetail','employees','employee','reports']){
    await page.evaluate(screen=>{repositoryProject='archive1';go(screen)},screen);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),screen+' horizontal overflow');
  }
  assert.deepEqual(errors,[]);
  console.log('PASS: project collections, employee add/remove and reassignment, daily/monthly accounting, sample screenshot history, cadence/pausing/clock-out, persistence, export and responsive screens.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
